kind: Service
apiVersion: v1
metadata:
  name: nodejs-app
  namespace: myapp
spec:
  type: LoadBalancer
  selector:
    app: nodejs-app
  ports:
    - name: http
      protocol: TCP
      port: 8050
      targetPort: 8050
